export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 13,
      category: 'smartwatch',
      title: 'boAt Ultima Chronos ',
      imgSrc: 'https://m.media-amazon.com/images/I/71QaOOBZ7LL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/8lVRVgo',
      description: ' boAt Ultima Chronos Energy & Sleep Score,IP67, Smart Watch for Men & Women(Brown Leather)',
      price: '18000',
    },
    {
      id: 17,
      category: 'earbuds',
      title: 'Boult x Mustang',
      imgSrc: 'https://m.media-amazon.com/images/I/719xn0KawFL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/98xcpUH',
      description: ' Boult x Mustang Torq Newly Launched Truly Wireless in Ear Earbuds with 50H Playtime, App Support',
      price: '',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 10,
      category: 'tv',
      title: 'Xiaomi Smart Google TV',
      imgSrc: 'https://m.media-amazon.com/images/I/71jsR3zkxJL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/8rMPhrM',
      description: 'Xiaomi 165 cm (65 inches) X Series 4K Ultra HD Smart Google TV L65M8-A2IN (Black) ',
      price: '59999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 11,
      category: 'tv',
      title: 'Panasonic HD Smart TV',
      imgSrc: 'https://m.media-amazon.com/images/I/71-hejEaChL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/hij336e',
      description: 'Panasonic 164 cm (65 inches) 4K Ultra HD Smart LED Google TV TH-65MX660DX (Black)',
      price: '56999',
    },
    {
      id: 12,
      category: 'tv',
      title: 'IBELL TV',
      imgSrc: 'https://m.media-amazon.com/images/I/61E2tVBELEL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/5Sb781p',
      description: ' IBELL 109 cm (43 Inches) Smart Full HD LED TV, Android 9.0, Wide Screen (LES435SE, Black)',
      price: '68999',
    },
    {
      id: 14,
      category: 'smartwatch',
      title: 'Noise Smart Watch',
      imgSrc: 'https://m.media-amazon.com/images/I/61khLNWFnHL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/7EhmlcS',
      description: ' Noise Newly Launched Quad Call 1.81" Display, Bluetooth Calling Smart Watch',
      price: '20000',
    },
    {
      id: 19,
      category: 'computer',
      title: 'Core I5 Desktop ',
      imgSrc: 'https://m.media-amazon.com/images/I/71snht4ZY+L._SL1500_.jpg',
      amazonLink: 'https://amzn.in/d/fvQmSqx',
      description: ' Core I5 Desktop Complete Computer System For Home&Business (Core I5 3Rd Generation,4Gb Ram-120Gb Ssd-500Gb Hdd)Windows 10 Pro,Intel,Black',
      price: '45000',
    },
    
    
    {
      id: 15,
      category: 'smartwatch',
      title: 'Fire-Boltt Ninja ',
      imgSrc: 'https://m.media-amazon.com/images/I/61fTfbdaszL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/aK3IzeD',
      description: 'Fire-Boltt Ninja Call Pro Max 51.05mm (2.01 inch) Display Smart Watch (Black) ',
      price: '8999',
    },
    {
      id: 16,
      category: 'earbuds',
      title: 'boAt Airdopes ',
      imgSrc: 'https://m.media-amazon.com/images/I/614gbl-O98L._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/cr0AUx0',
      description: ' boAt Airdopes 311 Pro Truly Wireless in Ear Ear Buds Tech(Active Black)',
      price: '',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
    {
      id: 18,
      category: 'computer',
      title: 'HP Compaq 19',
      imgSrc: 'https://m.media-amazon.com/images/I/61IHsPZ0A8L._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/9JebDJi',
      description: ' HP Compaq 19" HD All-in-One Desktop Computer Set (Intel i3 2nd Gen| 8 GB RAM| 500 GB HDD| 19" HD LED Monitor| KB & Mouse| Speakers| WiFi| Windows 10 Pro| MS Office)',
      price: '',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
  ]